name = "Fabric server perf modpack"
author = "Me"
version = "0.0.1"
description = "Fabric server perf modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4658371a9001ef518d43960ec72bbb0af16744cdf6f25644dee963b7ee70a953"

[versions]
fabric = "0.16.2"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21.1"]
