name = "Fabric server perf modpack"
author = "Me"
version = "0.0.1"
description = "Fabric server perf modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "310def2d29d3eee865c79bbe642c8863001440fbf6de8be2929727ca46f90284"

[versions]
fabric = "0.16.2"
minecraft = "1.21"
