name = "Fabric server perf modpack"
author = "Me"
version = "0.0.1"
description = "Fabric server perf modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20907119ea636d7c8f835d19216707e503d3d9b060f0465ff00ec5c76b98a805"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21.1"]
