name = "Fabric server perf modpack"
author = "Me"
version = "0.0.1"
description = "Fabric server perf modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acaffc1584fed6676b57eb793c616a0d4b8b307fa2301feab8d3ac2a69ecc2cd"

[versions]
fabric = "0.16.2"
minecraft = "1.21"
