name = "Fabric server perf modpack"
author = "Me"
version = "0.0.1"
description = "Fabric server perf modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "668979d51953b14aecaf1e301af23870c32aac09872b8798924da5ec491f9806"

[versions]
fabric = "0.16.2"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21.1"]
