name = "Fabric server perf modpack"
author = "Me"
version = "0.0.1"
description = "Fabric server perf modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38c64dd6932df86debd5ee2b4d6d8d55d218270eab468698f9848069b2403987"

[versions]
fabric = "0.16.2"
minecraft = "1.21"
