name = "vanilla-world"
author = "harkin"
version = "0.0.1"
description = "Mostly vanilla Fabric server pack, designed to improve performance primarily and disable some really annoying MC parts. Some extra structure generation is added to spice up the water"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b64492bce0d8c186c394efff3894687be0f100dc7a5e1066c03cf55a822f2360"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
