name = "vanilla-world"
author = "harkin"
version = "0.0.1"
description = "Mostly vanilla Fabric server pack, designed to improve performance primarily and disable some really annoying MC parts. Some extra structure generation is added to spice up the water"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e236e7a8b361000371970f6c1de0923942c8b89665d2cd094b211d55b646136c"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
