name = "vanilla-world"
author = "harkin"
version = "0.0.1"
description = "Mostly vanilla Fabric server pack, designed to improve performance primarily and disable some really annoying MC parts. Some extra structure generation is added to spice up the water"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea74431f029c45191aa8bfe52caf1502d60e3f2dbdf5616e66f3b3b8c17da446"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
