name = "vcraft"
author = "harkin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0da341a9bae176e72fded0bd899d2885724b7ef86ec836c8edac15975c3567b6"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
