name = "vcraft"
author = "harkin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee9b7110e1258692c385189bcf19a0a4efc4269f00b8da083e0968f13aaa44bc"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
