name = "vcraft"
author = "harkin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3d1d929652b3c1e9d3a400ee7f4a820fc9bd96d2e2fc6849c2818fa44f96989"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
