name = "vcraft"
author = "harkin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f9c5b02df005389b53c86b9d2d39ac053ad2e9d2cf6cdcfea22f980e2d63514"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
