name = "hermitcrafts10"
author = "harkin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f735bbedeb9369c20baeb80cfdc3f5db40cee0d7c480022742d17aefcf36321b"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"
